// app/layout.js
import { Roboto } from 'next/font/google' 
import "@/styles/index.scss";
import PageTransition from "@/components/PageTransition";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Roboto({ subsets: ['latin'] }) 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={inter.className}>
        <PageTransition>
          <Header />
          <main className="container">{children}</main>
          <Footer />
        </PageTransition>
      </body>
    </html>
  );
}
